# Generated by Django 4.0.2 on 2022-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=100)),
                ('status', models.BooleanField(verbose_name=True)),
            ],
            options={
                'db_table': 'csvusertypes',
            },
        ),
    ]
