# Generated by Django 4.0.2 on 2022-03-11 11:26

import datetime
from django.db import migrations, models
import django.forms.widgets


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0002_csvusertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100, verbose_name=django.forms.widgets.PasswordInput)),
                ('verification_code', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
            ],
            options={
                'db_table': 'csv_user',
            },
        ),
        migrations.CreateModel(
            name='CsvUserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('schedule_time', models.DateTimeField()),
                ('set_alarm', models.DateTimeField()),
                ('venue', models.CharField(max_length=100, null=True)),
                ('event_type', models.CharField(max_length=100, null=True)),
                ('priority', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('status', models.BooleanField(default=True)),
                ('user_id', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'csv_userschedule',
            },
        ),
    ]
