# Generated by Django 4.0.2 on 2022-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvapp', '0003_csvuser_csvuserschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_url', models.FileField(upload_to='users/profile/')),
                ('user_email', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'csv_user_profile',
            },
        ),
        migrations.AlterField(
            model_name='csvuser',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='csvuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
